// Generated by CoffeeScript 1.8.0
(function() {
  var register, resetFields;

  $(document).ready(function() {
    var $donateTriggers, $form;
    $donateTriggers = $('.donations-grid .donate-trigger');
    $form = $('.form-mailchimp');
    $form.bootstrapValidator({
      submitButtons: 'button[type="submit"]',
      fields: {
        EMAIL: {
          validators: {
            notEmpty: {
              message: 'Por favor completa este campo'
            },
            emailAddress: {
              message: 'Introduce un correo electrónico válido'
            }
          }
        },
        FNAME: {
          validators: {
            notEmpty: {
              message: 'Por favor completa este campo'
            }
          }
        }
      }
    }).on('success.form.bv', function(e) {
      var $data, $this;
      e.preventDefault();
      $form.parent().addClass('ajax-on-send');
      $this = $(this);
      $data = {
        username: $this.find('input[name="username"]').val(),
        dc: $this.find('input[name="dc"]').val(),
        u: $this.find('input[name="u"]').val(),
        id: $this.find('input[name="id"]').val()
      };
      register($this, $data);
    });
    $('.overlay-error button').click(function(e) {
      e.preventDefault();
      $('.modal-content').removeClass('ajax-on-send ajax-error');
    });
  });

  register = function($form, $data) {
    var $modalContent;
    $modalContent = $form.parent();
    $.ajax({
      type: $form.attr('method'),
      url: '//' + $data.username + '.' + $data.dc + '.list-manage.com/subscribe/post-json?u=' + $data.u + '&id=' + $data.id,
      data: $form.serialize(),
      cache: false,
      dataType: 'jsonp',
      jsonp: 'c',
      contentType: "application/json; charset=utf-8",
      error: function(err) {
        console.log(err);
        $modalContent.addClass('ajax-error');
      },
      success: function(data) {
        if (data.result !== "success") {
          $modalContent.addClass('ajax-error');
          return console.log(data);
        } else {
          console.log(data);
          $modalContent.addClass('ajax-success');
          $form.find('input[name="EMAIL"]').val('');
          $form.find('input[name="FNAME"]').val('');
          $form.find('input[name="LNAME"]').val('');
          $form.find('textarea[name="MESSAGE"]').val('');
        }
      }
    });
  };

  resetFields = function() {
    var $form, $modalContent;
    $modalContent = $('.modal-content');
    $form = $('.form-mailchimp');
    $modalContent.removeClass('ajax-success').removeClass('ajax-error').removeClass('ajax-on-send');
    $modalContent.find($form).find('input[type=text], textarea').val('');
  };

}).call(this);
