// Generated by CoffeeScript 1.8.0
(function() {
  var animateQuickView;

  $(document).ready(function() {
    var $maxQuickWidth, $overlayClose, $quickviewGrid, $quickviewGridAnchor, $quickviewGridItem, $section, $sectionPos, $sliderFinalWidth;
    $sliderFinalWidth = 400;
    $maxQuickWidth = 900;
    $section = $('#profiles');
    $sectionPos = $section.position();
    $overlayClose = $('.overlay-close');
    $overlayClose.css({
      height: $(document).height()
    });
    $quickviewGrid = $('.quick-view-grid');
    $quickviewGridItem = $('li', $quickviewGrid);
    $quickviewGridAnchor = $('a', $quickviewGridItem);
    $quickviewGridAnchor.on('click', function(e) {
      var itemImage, selectedItem;
      e.preventDefault();
      selectedItem = $(this);
      itemImage = selectedItem.find('img').attr('src');
      $('.quick-view .img-wrapper img').attr('src', itemImage);
      $('body').addClass('profile-on');
      animateQuickView(selectedItem, $sliderFinalWidth, $maxQuickWidth, 'open');
    });
    $overlayClose.on('click', function(e) {
      var selectedItem;
      e.preventDefault();
      selectedItem = $(this);
      $('body').removeClass('profile-on');
      animateQuickView(selectedItem, $sliderFinalWidth, $maxQuickWidth, 'close');
    });
  });

  animateQuickView = function(item, finalWidth, maxQuickWidth, animationType) {
    var docHeight, finalHeight, finalLeft, finalTop, heightSelected, leftSelected, parentListItem, quickViewLeft, quickViewWidth, topSelected, widthSelected, windowHeight, windowWidth, _ref;
    parentListItem = item.parents('.item');
    topSelected = item.offset().top;
    leftSelected = item.offset().left;
    widthSelected = item.width();
    heightSelected = item.height();
    windowWidth = $(window).width();
    windowHeight = $(window).height();
    docHeight = $(document).height();
    finalLeft = (windowWidth - finalWidth) / 2;
    finalHeight = finalWidth * heightSelected / widthSelected;
    finalTop = (windowHeight - finalHeight) / 2;
    quickViewWidth = (_ref = windowWidth * .8 < maxQuickWidth) != null ? _ref : windowWidth * {
      .8: maxQuickWidth
    };
    quickViewLeft = (windowWidth - quickViewWidth) / 2;
    console.log(topSelected);
    if (animationType === 'open') {
      parentListItem.addClass('profile-on');
      $('.quick-view').css({
        'top': topSelected,
        'left': leftSelected,
        'width': widthSelected
      }).velocity({
        'top': finalTop + 'px',
        'left': finalLeft + 'px',
        'width': finalWidth + 'px'
      }, 1000, [400, 20]).addClass('is-visible');
    } else {
      parentListItem.removeClass('profile-on');
      $('.quick-view').css({
        'top': finalTop + 'px',
        'left': finalLeft + 'px',
        'width': finalWidth + 'px'
      }).velocity({
        'top': topSelected,
        'left': leftSelected,
        'width': widthSelected
      }, 1000, [400, 20]).removeClass('is-visible');
    }
  };

}).call(this);
