// Generated by CoffeeScript 1.8.0
(function() {
  var animateQuickView;

  $(document).ready(function() {
    var $maxQuickWidth, $overlayClose, $quickviewGrid, $quickviewGridAnchor, $quickviewGridItem, $sliderFinalWidth;
    $sliderFinalWidth = 400;
    $maxQuickWidth = 900;
    $overlayClose = $('.overlay-close');
    $quickviewGrid = $('.quick-view-grid');
    $quickviewGridItem = $('li', $quickviewGrid);
    $quickviewGridAnchor = $('a', $quickviewGridItem);
    $quickviewGridAnchor.on('click', function(e) {
      var selectedItem;
      e.preventDefault();
      selectedItem = $(this);
      console.log(selectedItem.offset().top);
      console.log($(window).height());
      $('body').addClass('profile-on');
      animateQuickView(selectedItem, $sliderFinalWidth, $maxQuickWidth, 'open');
    });
    $overlayClose.on('click', function(e) {
      e.preventDefault();
      $('body').removeClass('profile-on');
    });
  });

  animateQuickView = function(item, finalWidth, maxQuickWidth, animationType) {
    var finalHeight, finalLeft, finalTop, heightSelected, leftSelected, parentListItem, quickViewLeft, quickViewWidth, topSelected, widthSelected, windowHeight, windowWidth, _ref;
    parentListItem = item.parents('.item');
    topSelected = item.offset().top;
    leftSelected = item.offset().left;
    widthSelected = item.width();
    heightSelected = item.height();
    windowWidth = $(window).width();
    windowHeight = $(window).height();
    finalLeft = (windowWidth - finalWidth) / 2;
    finalHeight = finalWidth * heightSelected / widthSelected;
    finalTop = (windowHeight - finalHeight) / 2;
    quickViewWidth = (_ref = windowWidth * .8 < maxQuickWidth) != null ? _ref : windowWidth * {
      .8: maxQuickWidth
    };
    quickViewLeft = (windowWidth - quickViewWidth) / 2;
    if (animationType === 'open') {
      parentListItem.addClass('profile-on');
      $('.quick-view').css({
        "top": topSelected,
        "left": leftSelected,
        "width": widthSelected
      }).velocity({
        'top': topSelected + 'px',
        'left': finalLeft + 'px',
        'width': finalWidth + 'px'
      }, 1000, [400, 20]).addClass('is-visible');
    }
  };

}).call(this);
